using ExtensionsMethods.EventViewerHelper;
using FirebirdSql.Data.FirebirdClient;
using Npgsql;
using System.Text.RegularExpressions;

namespace LabWebMvc.MVC.Integracoes.Importacao
{
    public class ColunaInfo
    {
        public string Nome { get; set; } = string.Empty;
        public string Tipo { get; set; } = string.Empty;
        public int? Tamanho { get; set; }
        public int? Precisao { get; set; }
        public int? Escala { get; set; }
        public bool Nullable { get; set; }
        public string? ValorPadrao { get; set; }
        public bool IsAutoIncrement { get; set; }
        /// <summary>
        /// Charset da coluna no Firebird (ex: ASCII, NONE, WIN1252, UTF8).
        /// </summary>
        public string? Charset { get; set; }
        /// <summary>
        /// Tipo de coluna identity do PostgreSQL:
        /// "" = nao identity; "a" = GENERATED ALWAYS AS IDENTITY; "d" = GENERATED BY DEFAULT AS IDENTITY
        /// </summary>
        public string? IdentityType { get; set; }
    }

    public class MapeamentoColunas
    {
        public string NomeFirebird { get; set; } = string.Empty;
        public string NomePostgreSQL { get; set; } = string.Empty;
        public ColunaInfo? ColunaFirebird { get; set; }
        public ColunaInfo? ColunaPostgreSQL { get; set; }
        public bool Compativel { get; set; }
        public string? Incompatibilidade { get; set; }
        public string? Aviso { get; set; }
    }

    public class SchemaComparisonResult
    {
        public string TabelaFirebird { get; set; } = string.Empty;
        public string TabelaPostgreSQL { get; set; } = string.Empty;
        public List<MapeamentoColunas> Colunas { get; set; } = new();
        public List<string> ColunasApenasFirebird { get; set; } = new();
        public List<string> ColunasApenasPostgreSQL { get; set; } = new();
        public List<ColunaInfo> ColunasPostgreSQL { get; set; } = new();
        public List<ColunaInfo> ColunasObrigatoriasAusentes { get; set; } = new();
        public bool PodeImportar => Colunas.Any(c => c.Compativel);
        public List<string> ErrosBloqueantes => Colunas.Where(c => !string.IsNullOrEmpty(c.Incompatibilidade)).Select(c => $"{c.NomeFirebird}: {c.Incompatibilidade}").ToList();
        public List<string> Avisos => Colunas.Where(c => !string.IsNullOrEmpty(c.Aviso)).Select(c => $"{c.NomeFirebird}: {c.Aviso}").ToList();
    }

    public class DependenciaFk
    {
        public string TabelaFilha { get; set; } = string.Empty;
        public string ColunaFilha { get; set; } = string.Empty;
        public string TabelaPai { get; set; } = string.Empty;
        public string ColunaPai { get; set; } = string.Empty;
    }

    public interface ISchemaComparer
    {
        Task<SchemaComparisonResult> CompararSchemasAsync(string firebirdConnectionString, string postgresConnectionString, string tabelaFirebird, string tabelaPostgreSQL, Dictionary<string, string>? mapeamentoColunas = null, CancellationToken cancellationToken = default);
        Task<SchemaComparisonResult> CompararSchemasAsync(FbConnection firebirdConnection, string postgresConnectionString, string tabelaFirebird, string tabelaPostgreSQL, Dictionary<string, string>? mapeamentoColunas = null, CancellationToken cancellationToken = default);
        Task<long> ContarRegistrosFirebirdAsync(string firebirdConnectionString, string tabelaFirebird, CancellationToken cancellationToken = default);
        Task<long> ContarRegistrosFirebirdAsync(FbConnection firebirdConnection, string tabelaFirebird, CancellationToken cancellationToken = default);
        Task<long> ContarRegistrosExistentesAsync(string postgresConnectionString, string tabelaPostgreSQL, string primaryKeyColumn, CancellationToken cancellationToken = default);
        Task<List<DependenciaFk>> ObterDependenciasFkAsync(string postgresConnectionString, CancellationToken cancellationToken = default);
        List<string> OrdenarParaLimpeza(IEnumerable<string> tabelasSelecionadas, List<DependenciaFk> dependencias);
        List<string> OrdenarParaImportacao(IEnumerable<string> tabelasSelecionadas, List<DependenciaFk> dependencias);
    }

    public class SchemaComparer : ISchemaComparer
    {
        private readonly IEventLogHelper _eventLog;

        public SchemaComparer(IEventLogHelper eventLog)
        {
            _eventLog = eventLog;
        }

        public async Task<SchemaComparisonResult> CompararSchemasAsync(string firebirdConnectionString, string postgresConnectionString, string tabelaFirebird, string tabelaPostgreSQL, Dictionary<string, string>? mapeamentoColunas = null, CancellationToken cancellationToken = default)
        {
            using var conn = new FbConnection(firebirdConnectionString);
            await conn.OpenAsync(cancellationToken);
            return await CompararSchemasAsync(conn, postgresConnectionString, tabelaFirebird, tabelaPostgreSQL, mapeamentoColunas, cancellationToken);
        }

        public async Task<SchemaComparisonResult> CompararSchemasAsync(FbConnection firebirdConnection, string postgresConnectionString, string tabelaFirebird, string tabelaPostgreSQL, Dictionary<string, string>? mapeamentoColunas = null, CancellationToken cancellationToken = default)
        {
            var resultado = new SchemaComparisonResult
            {
                TabelaFirebird = tabelaFirebird,
                TabelaPostgreSQL = tabelaPostgreSQL
            };

            mapeamentoColunas ??= new Dictionary<string, string>();

            var colunasFirebird = await ObterColunasFirebirdAsync(firebirdConnection, tabelaFirebird, cancellationToken);
            var colunasPostgres = await ObterColunasPostgreSQLAsync(postgresConnectionString, tabelaPostgreSQL, cancellationToken);

            var mensagem = $"[SchemaComparer] Tabela {tabelaFirebird}->{tabelaPostgreSQL}: {colunasFirebird.Count} colunas Firebird, {colunasPostgres.Count} colunas PostgreSQL.";
            _eventLog.LogEventViewer(mensagem, "wInfo");
            if (colunasFirebird.Any())
            {
                _eventLog.LogEventViewer($"[SchemaComparer] Colunas Firebird: {string.Join(", ", colunasFirebird.Select(c => c.Nome))}", "wInfo");
            }
            if (colunasPostgres.Any())
            {
                _eventLog.LogEventViewer($"[SchemaComparer] Colunas PostgreSQL: {string.Join(", ", colunasPostgres.Select(c => c.Nome))}", "wInfo");
            }

            // Aplica mapeamento de nomes: se uma coluna Firebird tem nome diferente no PostgreSQL,
            // cria uma cópia virtual da coluna Firebird com o nome mapeado para fins de comparação.
            var colunasFirebirdMapeadas = colunasFirebird
                .Select(c =>
                {
                    if (mapeamentoColunas.TryGetValue(c.Nome, out var nomeMapeado))
                    {
                        return new ColunaInfo
                        {
                            Nome = nomeMapeado,
                            Tipo = c.Tipo,
                            Tamanho = c.Tamanho,
                            Precisao = c.Precisao,
                            Escala = c.Escala,
                            Nullable = c.Nullable,
                            Charset = c.Charset
                        };
                    }
                    return c;
                })
                .ToList();

            var nomesFirebird = colunasFirebirdMapeadas.Select(c => c.Nome.ToUpperInvariant()).ToHashSet();
            var nomesPostgres = colunasPostgres.Select(c => c.Nome.ToUpperInvariant()).ToHashSet();

            resultado.ColunasApenasFirebird = colunasFirebird.Where(c => !nomesPostgres.Contains(c.Nome.ToUpperInvariant()) && !mapeamentoColunas.ContainsKey(c.Nome)).Select(c => c.Nome).ToList();
            resultado.ColunasApenasPostgreSQL = colunasPostgres.Where(c => !nomesFirebird.Contains(c.Nome.ToUpperInvariant())).Select(c => c.Nome).ToList();

            foreach (var colunaFb in colunasFirebirdMapeadas)
            {
                var colunaPg = colunasPostgres.FirstOrDefault(c => c.Nome.Equals(colunaFb.Nome, StringComparison.OrdinalIgnoreCase));
                var nomeOriginalFirebird = colunasFirebird.First(c => c.Nome.Equals(colunaFb.Nome, StringComparison.OrdinalIgnoreCase) || (mapeamentoColunas.ContainsKey(c.Nome) && mapeamentoColunas[c.Nome].Equals(colunaFb.Nome, StringComparison.OrdinalIgnoreCase))).Nome;

                var mapeamento = new MapeamentoColunas
                {
                    NomeFirebird = nomeOriginalFirebird,
                    NomePostgreSQL = colunaPg?.Nome ?? colunaFb.Nome,
                    ColunaFirebird = colunasFirebird.FirstOrDefault(c => c.Nome.Equals(nomeOriginalFirebird, StringComparison.OrdinalIgnoreCase)),
                    ColunaPostgreSQL = colunaPg,
                    Compativel = colunaPg != null
                };

                if (colunaPg == null)
                {
                    mapeamento.Incompatibilidade = $"Coluna '{nomeOriginalFirebird}' existe no Firebird mas não no PostgreSQL";
                }
                else if (!TiposCompativeis(colunaFb.Tipo, colunaPg.Tipo))
                {
                    mapeamento.Aviso = $"Tipos diferentes: Firebird={colunaFb.Tipo}, PostgreSQL={colunaPg.Tipo}. Conversão automática será tentada.";
                }

                resultado.Colunas.Add(mapeamento);
            }

            resultado.ColunasPostgreSQL = colunasPostgres;

            // Detecta colunas obrigatorias do PostgreSQL ausentes no Firebird para log e tratamento posterior.
            var colunasMapeadasNomes = resultado.Colunas.Select(c => c.NomePostgreSQL.ToUpperInvariant()).ToHashSet();
            resultado.ColunasObrigatoriasAusentes = colunasPostgres
                .Where(pg => !colunasMapeadasNomes.Contains(pg.Nome.ToUpperInvariant()) && !pg.Nullable && !pg.IsAutoIncrement)
                .ToList();

            if (resultado.ColunasObrigatoriasAusentes.Any())
            {
                var descricaoDefaults = string.Join(", ", resultado.ColunasObrigatoriasAusentes.Select(c =>
                {
                    var valorDefault = ObterValorPadraoDescritivo(c);
                    return $"{c.Nome}={valorDefault}";
                }));
                var mensagemAusentes = $"[SchemaComparer] {tabelaPostgreSQL}: colunas obrigatorias ausentes no Firebird serao preenchidas com defaults seguros ({descricaoDefaults}).";
                _eventLog.LogEventViewer(mensagemAusentes, "wInfo");
            }

            return resultado;
        }

        private static string ObterValorPadraoDescritivo(ColunaInfo coluna)
        {
            var tipo = coluna.Tipo.ToUpperInvariant();
            if (tipo.Contains("INT") || tipo.Contains("SERIAL") || tipo.Contains("NUMERIC") || tipo.Contains("DECIMAL") || tipo.Contains("DOUBLE") || tipo.Contains("REAL") || tipo.Contains("FLOAT"))
                return "0";
            if (tipo.Contains("BOOL"))
                return "false";
            if (tipo.Contains("DATE") || tipo.Contains("TIME"))
                return "min-date";
            if (tipo.Contains("BYTEA"))
                return "empty-bytes";
            return "\"\"";
        }

        public async Task<long> ContarRegistrosFirebirdAsync(string firebirdConnectionString, string tabelaFirebird, CancellationToken cancellationToken = default)
        {
            using var conn = new FbConnection(firebirdConnectionString);
            await conn.OpenAsync(cancellationToken);
            return await ContarRegistrosFirebirdAsync(conn, tabelaFirebird, cancellationToken);
        }

        public async Task<long> ContarRegistrosFirebirdAsync(FbConnection firebirdConnection, string tabelaFirebird, CancellationToken cancellationToken = default)
        {
            using var cmd = new FbCommand($"SELECT COUNT(*) FROM \"{tabelaFirebird}\"", firebirdConnection);
            cmd.CommandTimeout = 60;
            var result = await cmd.ExecuteScalarAsync(cancellationToken);
            return Convert.ToInt64(result);
        }

        public async Task<long> ContarRegistrosExistentesAsync(string postgresConnectionString, string tabelaPostgreSQL, string primaryKeyColumn, CancellationToken cancellationToken = default)
        {
            using var conn = new NpgsqlConnection(postgresConnectionString);
            await conn.OpenAsync(cancellationToken);

            using var cmd = new NpgsqlCommand($"SELECT COUNT(*) FROM \"{tabelaPostgreSQL}\"", conn);
            cmd.CommandTimeout = 60;
            var result = await cmd.ExecuteScalarAsync(cancellationToken);
            return Convert.ToInt64(result);
        }

        public async Task<List<DependenciaFk>> ObterDependenciasFkAsync(string postgresConnectionString, CancellationToken cancellationToken = default)
        {
            var dependencias = new List<DependenciaFk>();
            const string sql = @"
                SELECT
                    tc.table_name AS tabela_filha,
                    kcu.column_name AS coluna_filha,
                    ccu.table_name AS tabela_pai,
                    ccu.column_name AS coluna_pai
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                    ON tc.constraint_name = kcu.constraint_name
                    AND tc.table_schema = kcu.table_schema
                JOIN information_schema.constraint_column_usage ccu
                    ON ccu.constraint_name = tc.constraint_name
                    AND ccu.table_schema = tc.table_schema
                WHERE tc.constraint_type = 'FOREIGN KEY'
                  AND tc.table_schema = current_schema()";

            using var conn = new NpgsqlConnection(postgresConnectionString);
            await conn.OpenAsync(cancellationToken);
            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.CommandTimeout = 60;
            using var reader = await cmd.ExecuteReaderAsync(cancellationToken);
            while (await reader.ReadAsync(cancellationToken))
            {
                dependencias.Add(new DependenciaFk
                {
                    TabelaFilha = reader.GetString(0),
                    ColunaFilha = reader.GetString(1),
                    TabelaPai = reader.GetString(2),
                    ColunaPai = reader.GetString(3)
                });
            }

            return dependencias;
        }

        public List<string> OrdenarParaLimpeza(IEnumerable<string> tabelasSelecionadas, List<DependenciaFk> dependencias)
        {
            return OrdenarTopologicamente(tabelasSelecionadas, dependencias, filhasPrimeiro: true);
        }

        public List<string> OrdenarParaImportacao(IEnumerable<string> tabelasSelecionadas, List<DependenciaFk> dependencias)
        {
            return OrdenarTopologicamente(tabelasSelecionadas, dependencias, filhasPrimeiro: false);
        }

        private static List<string> OrdenarTopologicamente(IEnumerable<string> tabelasSelecionadas, List<DependenciaFk> dependencias, bool filhasPrimeiro)
        {
            var tabelas = new HashSet<string>(tabelasSelecionadas, StringComparer.OrdinalIgnoreCase);
            var grafo = new Dictionary<string, HashSet<string>>(StringComparer.OrdinalIgnoreCase);
            var grafoInvertido = new Dictionary<string, HashSet<string>>(StringComparer.OrdinalIgnoreCase);

            foreach (var tabela in tabelas)
            {
                grafo[tabela] = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                grafoInvertido[tabela] = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            }

            foreach (var dep in dependencias)
            {
                if (!tabelas.Contains(dep.TabelaFilha) || !tabelas.Contains(dep.TabelaPai))
                    continue;

                grafo[dep.TabelaFilha].Add(dep.TabelaPai);
                grafoInvertido[dep.TabelaPai].Add(dep.TabelaFilha);
            }

            var resultado = new List<string>();
            var visitadas = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var pilha = new Stack<string>();

            // Ordenação topológica: visita recursivamente filhos antes dos pais.
            void Visitar(string tabela)
            {
                if (visitadas.Contains(tabela))
                    return;

                visitadas.Add(tabela);
                foreach (var vizinho in grafo[tabela])
                    Visitar(vizinho);

                pilha.Push(tabela);
            }

            foreach (var tabela in tabelas)
                Visitar(tabela);

            while (pilha.Count > 0)
                resultado.Add(pilha.Pop());

            // A pilha resultante tem filhos depois dos pais. Para limpeza queremos filhos primeiro;
            // para importação queremos pais primeiro.
            if (filhasPrimeiro)
                resultado.Reverse();

            return resultado;
        }

        private async Task<List<ColunaInfo>> ObterColunasFirebirdAsync(FbConnection connection, string tabela, CancellationToken cancellationToken)
        {
            var colunas = new List<ColunaInfo>();

            // Busca case-insensitive. No Firebird, nomes sem aspas ficam em maiusculo;
            // nomes com aspas (delimited identifiers) preservam o case.
            const string sql = @"
                SELECT 
                    TRIM(r.rdb$field_name) AS nome,
                    CASE f.rdb$field_type
                        WHEN 7 THEN 'SMALLINT'
                        WHEN 8 THEN 'INTEGER'
                        WHEN 10 THEN 'FLOAT'
                        WHEN 12 THEN 'DATE'
                        WHEN 13 THEN 'TIME'
                        WHEN 14 THEN 'CHAR'
                        WHEN 16 THEN 'BIGINT'
                        WHEN 27 THEN 'DOUBLE'
                        WHEN 35 THEN 'TIMESTAMP'
                        WHEN 37 THEN 'VARCHAR'
                        WHEN 40 THEN 'CSTRING'
                        WHEN 45 THEN 'BLOB_ID'
                        WHEN 261 THEN 'BLOB'
                        ELSE 'UNKNOWN'
                    END AS tipo,
                    f.rdb$field_length AS tamanho,
                    f.rdb$field_precision AS precisao,
                    f.rdb$field_scale AS escala,
                    CASE WHEN r.rdb$null_flag = 1 THEN 0 ELSE 1 END AS nullable,
                    (SELECT TRIM(c.rdb$character_set_name) FROM rdb$character_sets c WHERE c.rdb$character_set_id = f.rdb$character_set_id) AS charset
                FROM rdb$relation_fields r
                JOIN rdb$fields f ON f.rdb$field_name = r.rdb$field_source
                WHERE UPPER(TRIM(r.rdb$relation_name)) = UPPER(TRIM(@tabela))
                ORDER BY r.rdb$field_position";

            using var cmd = new FbCommand(sql, connection);
            cmd.Parameters.AddWithValue("tabela", tabela);
            cmd.CommandTimeout = 60;

            using var reader = await cmd.ExecuteReaderAsync(cancellationToken);
            while (await reader.ReadAsync(cancellationToken))
            {
                colunas.Add(new ColunaInfo
                {
                    Nome = reader.GetString(0),
                    Tipo = reader.IsDBNull(1) ? string.Empty : reader.GetString(1),
                    Tamanho = reader.IsDBNull(2) ? null : reader.GetInt32(2),
                    Precisao = reader.IsDBNull(3) ? null : reader.GetInt32(3),
                    Escala = reader.IsDBNull(4) ? null : reader.GetInt32(4),
                    Nullable = reader.GetInt32(5) == 1,
                    Charset = reader.IsDBNull(6) ? null : reader.GetString(6)
                });
            }

            return colunas;
        }

        private async Task<List<ColunaInfo>> ObterColunasPostgreSQLAsync(string connectionString, string tabela, CancellationToken cancellationToken)
        {
            var colunas = new List<ColunaInfo>();

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken);

            // Busca em todos os schemas do banco (exceto catálogos do sistema).
            // Prioriza o schema atual da conexao, mas nao depende exclusivamente dele.
            const string sql = @"
                SELECT 
                    a.attname AS column_name,
                    pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
                    NULL::integer AS character_maximum_length,
                    NULL::integer AS numeric_precision,
                    NULL::integer AS numeric_scale,
                    CASE WHEN a.attnotnull THEN 'NO' ELSE 'YES' END AS is_nullable,
                    n.nspname AS schema_name,
                    pg_catalog.pg_get_expr(d.adbin, d.adrelid) AS column_default,
                    a.attidentity::text AS identity_type
                FROM pg_catalog.pg_attribute a
                JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
                JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
                WHERE c.relname ILIKE @tabela
                  AND n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast')
                  AND a.attnum > 0
                  AND NOT a.attisdropped
                ORDER BY 
                    CASE WHEN n.nspname = current_schema() THEN 0 ELSE 1 END,
                    n.nspname,
                    a.attnum";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("tabela", tabela);
            cmd.CommandTimeout = 60;

            using var reader = await cmd.ExecuteReaderAsync(cancellationToken);
            string? schemaEncontrado = null;
            while (await reader.ReadAsync(cancellationToken))
            {
                var tipo = reader.GetString(1);
                // Simplifica tipos como character varying(50) -> character varying
                var tipoBase = tipo.Split('(')[0].Trim();
                schemaEncontrado ??= reader.GetString(6);

                var valorPadrao = reader.IsDBNull(7) ? null : reader.GetString(7);
                var identityType = reader.IsDBNull(8) ? null : reader.GetString(8);

                // Extrai tamanho/precisao/escala do format_type, ex: character varying(15), numeric(10,2)
                int? tamanho = null;
                int? precisao = null;
                int? escala = null;
                var match = Regex.Match(tipo, @"\((\d+)(?:\s*,\s*(\d+))?\)");
                if (match.Success)
                {
                    if (int.TryParse(match.Groups[1].Value, out var n1))
                    {
                        if (tipoBase.Contains("NUMERIC") || tipoBase.Contains("DECIMAL"))
                        {
                            precisao = n1;
                            if (match.Groups[2].Success && int.TryParse(match.Groups[2].Value, out var n2))
                                escala = n2;
                        }
                        else
                        {
                            tamanho = n1;
                        }
                    }
                }

                colunas.Add(new ColunaInfo
                {
                    Nome = reader.GetString(0),
                    Tipo = tipoBase,
                    Tamanho = tamanho,
                    Precisao = precisao,
                    Escala = escala,
                    Nullable = reader.GetString(5).Equals("YES", StringComparison.OrdinalIgnoreCase),
                    ValorPadrao = valorPadrao,
                    IsAutoIncrement = !string.IsNullOrEmpty(identityType) || (!string.IsNullOrEmpty(valorPadrao) && valorPadrao.Contains("nextval", StringComparison.OrdinalIgnoreCase)),
                    IdentityType = identityType
                });
            }

            return colunas;
        }

        private static bool TiposCompativeis(string tipoFirebird, string tipoPostgreSQL)
        {
            var fb = tipoFirebird.ToUpperInvariant();
            var pg = tipoPostgreSQL.ToUpperInvariant();

            if (fb.Contains("VARCHAR") || fb.Contains("CHAR"))
                return pg.Contains("VARCHAR") || pg.Contains("CHAR") || pg.Contains("TEXT") || pg.Contains("BOOL");

            if (fb.Contains("INTEGER") || fb.Contains("SMALLINT") || fb.Contains("BIGINT"))
                return pg.Contains("INT") || pg.Contains("SMALLINT") || pg.Contains("BIGINT") || pg.Contains("SERIAL") || pg.Contains("BOOL") || pg.Contains("NUMERIC") || pg.Contains("DECIMAL") || pg.Contains("DOUBLE") || pg.Contains("REAL") || pg.Contains("FLOAT");

            if (fb.Contains("NUMERIC") || fb.Contains("DECIMAL") || fb.Contains("DOUBLE") || fb.Contains("FLOAT"))
                return pg.Contains("NUMERIC") || pg.Contains("DECIMAL") || pg.Contains("DOUBLE") || pg.Contains("REAL") || pg.Contains("FLOAT") || pg.Contains("INT") || pg.Contains("SMALLINT") || pg.Contains("BIGINT") || pg.Contains("SERIAL") || pg.Contains("BOOL");

            if (fb.Contains("TIMESTAMP"))
                return pg.Contains("TIMESTAMP") || pg.Contains("DATE") || pg.Contains("TIME");

            if (fb.Contains("DATE") && !fb.Contains("TIMESTAMP"))
                return pg.Contains("DATE") || pg.Contains("TIMESTAMP");

            if (fb.Contains("TIME") && !fb.Contains("TIMESTAMP"))
                return pg.Contains("TIME") || pg.Contains("TIMESTAMP");

            if (fb.Contains("BLOB"))
                return pg.Contains("BYTEA") || pg.Contains("TEXT");

            if (fb.Contains("BOOLEAN"))
                return pg.Contains("BOOL") || pg.Contains("INT") || pg.Contains("SMALLINT") || pg.Contains("BIGINT");

            return true;
        }
    }
}
