line = '| Microsoft.EntityFrameworkCore.Relational | 8.0.19 | Suporte a bancos relacionais     |'
print(f'Linha completa: {len(line)} chars')
print(f'\nTexto: {line}')
print(f'\nAnálise:')
parts = line.split('|')
print(f'Parte 0: "{parts[0]}"')
print(f'Parte 1: "{parts[1]}" = {len(parts[1])} chars')
print(f'  Texto: "{parts[1].strip()}" = {len(parts[1].strip())} chars')
print(f'  Espaços extras: {len(parts[1]) - len(parts[1].strip())}')
print(f'Parte 2: "{parts[2]}" = {len(parts[2])} chars')
print(f'  Texto: "{parts[2].strip()}" = {len(parts[2].strip())} chars')
print(f'  Espaços extras: {len(parts[2]) - len(parts[2].strip())}')
print(f'Parte 3: "{parts[3]}" = {len(parts[3])} chars')
print(f'  Texto: "{parts[3].strip()}" = {len(parts[3].strip())} chars')
print(f'  Espaços extras: {len(parts[3]) - len(parts[3].strip())}')
