//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabWebMvc.MVC.Mensagens {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensError_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensError_pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabWebMvc.MVC.Mensagens.MensagensError_pt_BR", typeof(MensagensError_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível conectar neste momento.
        /// </summary>
        public static string ErroConexao {
            get {
                return ResourceManager.GetString("ErroConexao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível conectar neste momento.
        /// </summary>
        public static string ErroConexao1 {
            get {
                return ResourceManager.GetString("ErroConexao1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops.
        /// </summary>
        public static string ErroFalhou {
            get {
                return ResourceManager.GetString("ErroFalhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lista tem uma falha.
        /// </summary>
        public static string ErroLista {
            get {
                return ResourceManager.GetString("ErroLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso indisponível.
        /// </summary>
        public static string ErroLogin {
            get {
                return ResourceManager.GetString("ErroLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro não identificado.
        /// </summary>
        public static string ErroNaoIdentificado {
            get {
                return ResourceManager.GetString("ErroNaoIdentificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma falha inesperada no carregamento da página.
        /// </summary>
        public static string ErroPagina {
            get {
                return ResourceManager.GetString("ErroPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devido a uma falha, o registro não foi encontrado.
        /// </summary>
        public static string ErroRegistroFalhou {
            get {
                return ResourceManager.GetString("ErroRegistroFalhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não encontrado.
        /// </summary>
        public static string ErroRegistroNaoEncontrado {
            get {
                return ResourceManager.GetString("ErroRegistroNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não foi salvo.
        /// </summary>
        public static string ErroSalvar {
            get {
                return ResourceManager.GetString("ErroSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não foi salvo. Verifique.
        /// </summary>
        public static string ErroSalvarVerifique {
            get {
                return ResourceManager.GetString("ErroSalvarVerifique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não haviam dados modificados para serem atualizados.
        /// </summary>
        public static string ErroSemDadoAtualizado {
            get {
                return ResourceManager.GetString("ErroSemDadoAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível iniciar a aplicação.
        /// </summary>
        public static string ErroSistema {
            get {
                return ResourceManager.GetString("ErroSistema", resourceCulture);
            }
        }
    }
}
